### ISSUE TITLE
Screen type not working.

### ISSUE THREAD

**Issue by derpystego** [quinn-semele/expanded-storage#10]
For some reason when i try to change the config to anything that isn't the "Single page screen" it simply doesn't work?.
It just continues to show the single page screen even though it says that one of the others is my preference currently.
the client config looks fine and is "paginated"
I am on Forge 1.20.1 47.2.17 & expanded storage version 10.2.1

I haven't been able to find out if its a conflict of other mods either.

**Comment by quinn-semele** [comment]
Sorry been taking a little break,
The mod was designed so that if a single page would fit on your screen it will always use the single type, I believe I had added an option in the config to change that behaviour however I've not reviewed it in a while so it's possible it doesn't work, but in case it does still work it should be called `prefer_smaller_screens`, and if it doesn't I'll add it to the `10.3.0` changelog which I'll try work on again soon.

**Comment by quinn-semele** [comment]
I've added an option `fit_vanilla_constraints` which forces the inventory to only use a `9x6` or smaller inventory size which may not be the most ideal solution however I think this should address the issue and work well enough as a stopgap until I can code something proper for the mod rewrite.
![image](https://github.com/quinn-semele/expanded-storage/assets/160874100/56099b42-3285-40e1-970b-71b9f22b3e37)

**Comment by quinn-semele** [comment]
Maybe fixed? Hopefully I can come up with some better configuration options in the future...

https://modrinth.com/mod/expanded-storage/version/10.3.0-beta.1+forge
