### ISSUE TITLE
Duping gold barrel using Ars nouveau.

### ISSUE THREAD

**Issue by dunesea** [quinn-semele/expanded-storage#33]
I have found a bug while playing a mod pack called Craftoria and using the Ars Nouveau novice spell book with the spell setup of (Projectile) (Break) for the spell and holding shift and casting that spell right next to the barrel opens the inventory and breaks it but it instead drops the barrel and immediately gets replaced and this can happen indefinitely as long as your in the range to open the barrel. I have yet to test any other barrels.

**Comment by quinn-semele** [comment]
Hey, I have a hard time beliving this is an issue with my mod specifically, can you also report this issue to Ars Nouveau please.

**Comment by 800020h** [comment]
in my testing in craftoria it only seems to affect expanded storage barrels
`projectile -> interact -> break` also triggers it from out of normal interaction range

**Comment by quinn-semele** [comment]
I've had others state the issue exists with vanilla chests too and how my chests / barrels open is no different from vanilla...

**Comment by quinn-semele** [comment]
Okay, I think there's 2 issues here,
1. Ars Nouveau's spell book still interacts with blocks even when the user is holding shift which shouldn't be the case given how every other item interaction works.
2. Containers (the class that actually holds the items within a block and handles the server side of the gui you interract with) can still exist despite a block being destroyed which is an issue on my end that I need to fix.

**Comment by quinn-semele** [comment]
Should be fixed in 14.1.6, if not then it's not on my side anymore.

CurseForge: [NeoForge](<https://curseforge.com/minecraft/mc-mods/expanded-storage/files/5831317>) | [Fabric](<https://curseforge.com/minecraft/mc-mods/expanded-storage/files/5831318>) | [Quilt](<https://curseforge.com/minecraft/mc-mods/expanded-storage/files/5831319>)
Modrinth: [NeoForge](<https://modrinth.com/mod/jCCPlP3c/version/K3vtoVIT>) | [Fabric](<https://modrinth.com/mod/jCCPlP3c/version/QK76Ea4g>) | [Quilt](<https://modrinth.com/mod/jCCPlP3c/version/L1Xul8h2>)
